development:
  dialect: "sqlite3"
  database: "./json-resource_development.sqlite"

test:
  dialect: "sqlite3"
  database: "./json-resource_test.sqlite"

production:
  dialect: "sqlite3"
  database: "./json-resource_production.sqlite"
